datasets:
  aire20:
    path: "data/raw/datos_aire/DatosAire2020.csv"
    delim: ";"
  aire21:
    path: "data/raw/datos_aire/DatosAire2021.csv"
    delim: ";"
  aire22:
    path: "data/raw/datos_aire/DatosAire2022.csv"
    delim: ";"
  aire23:
    path: "data/raw/datos_aire/DatosAire2023.csv"
    delim: ";"
  aire24C6H6:
    path: "data/raw/datos_aire/DatosAire2024/C6H6_HH_2024.csv"
    delim: ";"
  aire24CO:
    path: "data/raw/datos_aire/DatosAire2024/CO_HH_2024.csv"
    delim: ";"
  aire24NO:
    path: "data/raw/datos_aire/DatosAire2024/NO_HH_2024.csv"
    delim: ";"
  aire24NO2:
    path: "data/raw/datos_aire/DatosAire2024/NO2_HH_2024.csv"
    delim: ";"
  aire24NOx:
    path: "data/raw/datos_aire/DatosAire2024/Nox_HH_2024.csv"
    delim: ";"
  aire24O3:
    path: "data/raw/datos_aire/DatosAire2024/O3_HH_2024.csv"
    delim: ";"
  aire24PM10:
    path: "data/raw/datos_aire/DatosAire2024/PM10_HH_2024.csv"
    delim: ";"
  aire24PM25:
    path: "data/raw/datos_aire/DatosAire2024/PM25_HH_2024.csv"
    delim: ";"
  aire24SO2:
    path: "data/raw/datos_aire/DatosAire2024/SO2_HH_2024.csv"
    delim: ";"
  dim_variable_aire_csv:
    path: "data/raw/static_files/variable_aire.csv"
    delim: ","
  aemet_climatologia_diaria:
    path: "data/raw/datos_meteo/Datos_aemt_Eva/aemet_diarios_2020_2024.csv"
    delim: ","
  dim_variable_meteo_csv:
    path: "data/raw/static_files/variables_meteo.csv"
    delim: ","