pipelines:
  - name: "aire_normalizado"
    sql_file: "sql/dn_air_transformer.sql"
    output_parquet: "data/normalized/fact/calidad_aire_historico.parquet"
    sources:
      aire20: "aire20"
      aire21: "aire21"
      aire22: "aire22"
      aire23: "aire23"
      C6H6: "aire24C6H6"
      CO: "aire24CO"
      NO_: "aire24NO"
      NO2: "aire24NO2"
      NOx: "aire24NOx"
      O3: "aire24O3"
      PM10: "aire24PM10"
      PM25: "aire24PM25"
      SO2: "aire24SO2"
      dimension_unidades_aire: "dim_variable_aire_csv"


  - name: "seed_variables_aire"
    sql_file: "sql/seed_table_creator.sql"
    output_parquet: "data/normalized/static_files/seed_variable_aire.parquet"
    sources:
      variable_src: "dim_variable_aire_csv"


  - name: "meteo_aemet_normalizado"
    sql_file: "sql/dn_meteo_transformer.sql"
    output_parquet: "data/normalized/fact/meteo_aemet_historico.parquet"
    sources:
      aemet_raw: "aemet_climatologia_diaria"
      seed_meteo: "dim_variable_meteo_csv"

  - name: "seed_variable_meteo"
    sql_file: "sql/seed_table_creator.sql"
    output_parquet: "data/normalized/static_files/seed_variable_meteo.parquet"
    sources:
      variable_src: "dim_variable_meteo_csv"