datasets:
  aire_normalized_ds:
    path: "data/normalized/fact/calidad_aire_historico.parquet"
    delim: ";"
  seed_rangos_aire:
    path: "data/normalized/static_files/seed_rango_variables_aire.parquet"
  meteo_normalized_ds:
    path: "data/normalized/fact/meteo_aemet_historico.parquet"
    delim: ";"
  seed_festivos:
    path: "data/normalized/static_files/seed_festivos.parquet"
    delim: ";"


  seed_estaciones_aire:
    path: "data/raw/static_files/metadata_estaciones_aire.csv"
    delim: ","

  seed_estaciones_meteo:
    path: "data/raw/static_files/metadata_estaciones_meteo.csv"
    delim: ","