pipelines:
  - name: "aire_enriched"
    sql_file: "sql/enriched_aire.sql"
    output_parquet: "data/enriched/fact/calidad_aire_final.parquet"
    sources:
      aire_normalized: "aire_normalized_ds"
      seed_rangos_aire: "seed_rangos_aire"
      tabla_festivos: "seed_festivos"

  - name: "meteo_enriched"
    sql_file: "sql/enriched_meteo.sql"
    output_parquet: "data/enriched/fact/meteo_final.parquet"
    sources:
      meteo_normalized: "meteo_normalized_ds"

  - name: "metadata_estaciones"
    sql_file: "sql/enriched_estaciones.sql"
    output_parquet: "data/enriched/static_files/metadata_estaciones_final.parquet"
    sources:
      seed_estaciones: "seed_estaciones"