pipelines:
  # FACTS
  - name: "aire_enriched"
    sql_file: "sql/enriched_aire.sql"
    output_parquet: "data/enriched/fact/calidad_aire_final.parquet"
    sources:
      aire_normalized: "aire_normalized_ds"
      seed_rangos_aire: "seed_rangos_aire"
      tabla_festivos: "seed_festivos"
      metadata_estaciones_aire: "seed_estaciones_aire"
    tests:
      - name: "No hay calidades nulas"
        sql_file: "tests/calidades_no_null.sql"


  - name: "meteo_enriched"
    sql_file: "sql/enriched_meteo.sql"
    output_parquet: "data/enriched/fact/meteo_final.parquet"
    sources:
      meteo_normalized: "meteo_normalized_ds"

  # DIMS
  - name: "metadata_estaciones_aire"
    sql_file: "sql/enriched_estaciones_aire.sql"
    output_parquet: "data/enriched/dims/dim_estaciones_aire.parquet"
    sources:
      seed_estaciones_aire: "seed_estaciones_aire"
      seed_estaciones_meteo: "seed_estaciones_meteo"

  - name: "metadata_estaciones_meteo"
    sql_file: "sql/enriched_estaciones_meteo.sql"
    output_parquet: "data/enriched/dims/dim_estaciones_meteo.parquet"
    sources:
      seed_estaciones: "seed_estaciones_meteo"